services:
  - type: web
    name: tetris-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn tetris_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tetris_project.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
