services:
  - type: web
    name: tetris-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tetris_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tetris_project.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
